//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLEOC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SL_AVATAR
    {
        public SL_AVATAR()
        {
            this.SL_AVATAR_IMAGE = new HashSet<SL_AVATAR_IMAGE>();
            this.SL_AVATAR_PROFILE = new HashSet<SL_AVATAR_PROFILE>();
            this.SL_CHAT = new HashSet<SL_CHAT>();
            this.SL_IMAGE = new HashSet<SL_IMAGE>();
            this.SL_LOCATION = new HashSet<SL_LOCATION>();
            this.SL_MP_GAME_SESSION = new HashSet<SL_MP_GAME_SESSION>();
            this.SL_MP_GAME_SESSION1 = new HashSet<SL_MP_GAME_SESSION>();
            this.SL_ONLINE_AVATAR = new HashSet<SL_ONLINE_AVATAR>();
            this.SL_POSITION = new HashSet<SL_POSITION>();
            this.SL_SP_GAME_SESSION = new HashSet<SL_SP_GAME_SESSION>();
            this.SL_VISITOR = new HashSet<SL_VISITOR>();
            this.SLEOC_TEAM_MEMBER = new HashSet<SLEOC_TEAM_MEMBER>();
        }
    
        public System.Guid AvatarID { get; set; }
        public string AvatarName { get; set; }
        public System.DateTime AvatarRegisterDate { get; set; }
    
        public virtual ICollection<SL_AVATAR_IMAGE> SL_AVATAR_IMAGE { get; set; }
        public virtual ICollection<SL_AVATAR_PROFILE> SL_AVATAR_PROFILE { get; set; }
        public virtual ICollection<SL_CHAT> SL_CHAT { get; set; }
        public virtual ICollection<SL_IMAGE> SL_IMAGE { get; set; }
        public virtual ICollection<SL_LOCATION> SL_LOCATION { get; set; }
        public virtual ICollection<SL_MP_GAME_SESSION> SL_MP_GAME_SESSION { get; set; }
        public virtual ICollection<SL_MP_GAME_SESSION> SL_MP_GAME_SESSION1 { get; set; }
        public virtual ICollection<SL_ONLINE_AVATAR> SL_ONLINE_AVATAR { get; set; }
        public virtual ICollection<SL_POSITION> SL_POSITION { get; set; }
        public virtual ICollection<SL_SP_GAME_SESSION> SL_SP_GAME_SESSION { get; set; }
        public virtual ICollection<SL_VISITOR> SL_VISITOR { get; set; }
        public virtual ICollection<SLEOC_TEAM_MEMBER> SLEOC_TEAM_MEMBER { get; set; }
    }
}
