//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLEOC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SL_AVATAR_PROFILE_USER_PROFILE
    {
        public int AvatarUserID { get; set; }
        public string AvatarUsername { get; set; }
        public int UserId { get; set; }
    
        public virtual SL_AVATAR_PROFILE SL_AVATAR_PROFILE { get; set; }
    }
}
