//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLEOC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SL_AVATAR_IMAGE
    {
        public int AvatarImageID { get; set; }
    
        public virtual SL_AVATAR SL_AVATAR { get; set; }
        public virtual SL_IMAGE SL_IMAGE { get; set; }
    }
}
