//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLEOC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SL_AVATAR_PROFILE
    {
        public SL_AVATAR_PROFILE()
        {
            this.SL_AVATAR_PROFILE_USER_PROFILE = new HashSet<SL_AVATAR_PROFILE_USER_PROFILE>();
        }
    
        public string ProfileHash { get; set; }
    
        public virtual SL_AVATAR SL_AVATAR { get; set; }
        public virtual ICollection<SL_AVATAR_PROFILE_USER_PROFILE> SL_AVATAR_PROFILE_USER_PROFILE { get; set; }
    }
}
