//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLEOC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SL_CHAT
    {
        public long ChatID { get; set; }
        public string ChatMessage { get; set; }
        public System.DateTime ChatTimeStamp { get; set; }
        public bool ChatIsFromSL { get; set; }
    
        public virtual SL_AVATAR SL_AVATAR { get; set; }
        public virtual SL_LOCATION SL_LOCATION { get; set; }
    }
}
