//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLEOC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SL_GAME
    {
        public SL_GAME()
        {
            this.SL_GAME_VERSION = new HashSet<SL_GAME_VERSION>();
        }
    
        public int GameID { get; set; }
        public string GameName { get; set; }
        public bool GameIsMultiplayer { get; set; }
        public string GameDescription { get; set; }
        public bool GameIsReleased { get; set; }
    
        public virtual ICollection<SL_GAME_VERSION> SL_GAME_VERSION { get; set; }
    }
}
