//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLEOC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SL_GAME_VERSION
    {
        public SL_GAME_VERSION()
        {
            this.SL_MP_GAME_SESSION = new HashSet<SL_MP_GAME_SESSION>();
            this.SL_SP_GAME_SESSION = new HashSet<SL_SP_GAME_SESSION>();
        }
    
        public int GameVersionID { get; set; }
        public string GameVersionName { get; set; }
        public string GameVersionDescription { get; set; }
        public int GameVersionPlayCount { get; set; }
    
        public virtual SL_GAME SL_GAME { get; set; }
        public virtual ICollection<SL_MP_GAME_SESSION> SL_MP_GAME_SESSION { get; set; }
        public virtual ICollection<SL_SP_GAME_SESSION> SL_SP_GAME_SESSION { get; set; }
    }
}
