//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLEOC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SL_IMAGE
    {
        public SL_IMAGE()
        {
            this.SL_AVATAR_IMAGE = new HashSet<SL_AVATAR_IMAGE>();
            this.SL_LOCATION_IMAGE = new HashSet<SL_LOCATION_IMAGE>();
        }
    
        public int ImageID { get; set; }
        public byte[] ImageData { get; set; }
        public string ImageURL { get; set; }
        public bool ImageIsFile { get; set; }
        public string ImageTitle { get; set; }
        public System.DateTime ImageUploadDate { get; set; }
        public string ImageMimeType { get; set; }
    
        public virtual SL_AVATAR SL_AVATAR { get; set; }
        public virtual ICollection<SL_AVATAR_IMAGE> SL_AVATAR_IMAGE { get; set; }
        public virtual ICollection<SL_LOCATION_IMAGE> SL_LOCATION_IMAGE { get; set; }
    }
}
