//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLEOC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SL_LOCATION_SETTINGS
    {
        public int LocationSettingsID { get; set; }
        public Nullable<bool> LocationChatIsOn { get; set; }
    
        public virtual SL_LOCATION SL_LOCATION { get; set; }
    }
}
