//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLEOC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SL_LOCATION
    {
        public SL_LOCATION()
        {
            this.SL_CHAT = new HashSet<SL_CHAT>();
            this.SL_LOCATION_IMAGE = new HashSet<SL_LOCATION_IMAGE>();
            this.SL_LOCATION_SETTINGS = new HashSet<SL_LOCATION_SETTINGS>();
            this.SL_ONLINE_AVATAR = new HashSet<SL_ONLINE_AVATAR>();
            this.SL_VISITOR = new HashSet<SL_VISITOR>();
            this.SL_TAG = new HashSet<SL_TAG>();
        }
    
        public int LocationID { get; set; }
        public string LocationName { get; set; }
        public double LocationX { get; set; }
        public double LocationY { get; set; }
        public double LocationZ { get; set; }
        public string LocationDescription { get; set; }
    
        public virtual SL_AVATAR SL_AVATAR { get; set; }
        public virtual ICollection<SL_CHAT> SL_CHAT { get; set; }
        public virtual ICollection<SL_LOCATION_IMAGE> SL_LOCATION_IMAGE { get; set; }
        public virtual ICollection<SL_LOCATION_SETTINGS> SL_LOCATION_SETTINGS { get; set; }
        public virtual SL_SIM SL_SIM { get; set; }
        public virtual ICollection<SL_ONLINE_AVATAR> SL_ONLINE_AVATAR { get; set; }
        public virtual ICollection<SL_VISITOR> SL_VISITOR { get; set; }
        public virtual ICollection<SL_TAG> SL_TAG { get; set; }
    }
}
