//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLEOC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SL_POSITION
    {
        public int PositionID { get; set; }
        public double PositionX { get; set; }
        public double PositionY { get; set; }
        public double PositionZ { get; set; }
        public System.DateTime PositionTimeStamp { get; set; }
    
        public virtual SL_AVATAR SL_AVATAR { get; set; }
        public virtual SL_SIM SL_SIM { get; set; }
    }
}
