//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLEOC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SL_SIM
    {
        public SL_SIM()
        {
            this.SL_LOCATION = new HashSet<SL_LOCATION>();
            this.SL_POSITION = new HashSet<SL_POSITION>();
        }
    
        public int SimID { get; set; }
        public string SimName { get; set; }
        public string SimDescription { get; set; }
    
        public virtual ICollection<SL_LOCATION> SL_LOCATION { get; set; }
        public virtual ICollection<SL_POSITION> SL_POSITION { get; set; }
    }
}
