//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLEOC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SL_TAG
    {
        public SL_TAG()
        {
            this.SL_LOCATION = new HashSet<SL_LOCATION>();
        }
    
        public int TagID { get; set; }
        public string TagName { get; set; }
        public string TagDescription { get; set; }
        public string TagIconName { get; set; }
    
        public virtual ICollection<SL_LOCATION> SL_LOCATION { get; set; }
    }
}
