//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLEOC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLEOC_TEAM_MEMBER
    {
        public int TeamMemberID { get; set; }
    
        public virtual SL_AVATAR SL_AVATAR { get; set; }
        public virtual SLEOC_TEAM SLEOC_TEAM { get; set; }
    }
}
