//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLEOC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLEOC_TEAM
    {
        public SLEOC_TEAM()
        {
            this.SLEOC_TEAM_MEMBER = new HashSet<SLEOC_TEAM_MEMBER>();
        }
    
        public int TeamID { get; set; }
        public string TeamName { get; set; }
        public string TeamDescription { get; set; }
    
        public virtual ICollection<SLEOC_TEAM_MEMBER> SLEOC_TEAM_MEMBER { get; set; }
    }
}
