//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLEOC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cdashdbEntities : DbContext
    {
        public cdashdbEntities()
            : base("name=cdashdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SL_AVATAR> SL_AVATAR { get; set; }
        public virtual DbSet<SL_SIM> SL_SIM { get; set; }
        public virtual DbSet<SL_AVATAR_IMAGE> SL_AVATAR_IMAGE { get; set; }
        public virtual DbSet<SL_AVATAR_PROFILE> SL_AVATAR_PROFILE { get; set; }
        public virtual DbSet<SL_AVATAR_PROFILE_USER_PROFILE> SL_AVATAR_PROFILE_USER_PROFILE { get; set; }
        public virtual DbSet<SL_CHAT> SL_CHAT { get; set; }
        public virtual DbSet<SL_GAME> SL_GAME { get; set; }
        public virtual DbSet<SL_GAME_VERSION> SL_GAME_VERSION { get; set; }
        public virtual DbSet<SL_IMAGE> SL_IMAGE { get; set; }
        public virtual DbSet<SL_LOCATION> SL_LOCATION { get; set; }
        public virtual DbSet<SL_LOCATION_IMAGE> SL_LOCATION_IMAGE { get; set; }
        public virtual DbSet<SL_LOCATION_SETTINGS> SL_LOCATION_SETTINGS { get; set; }
        public virtual DbSet<SL_MP_GAME_SESSION> SL_MP_GAME_SESSION { get; set; }
        public virtual DbSet<SL_ONLINE_AVATAR> SL_ONLINE_AVATAR { get; set; }
        public virtual DbSet<SL_POSITION> SL_POSITION { get; set; }
        public virtual DbSet<SL_SP_GAME_SESSION> SL_SP_GAME_SESSION { get; set; }
        public virtual DbSet<SL_TAG> SL_TAG { get; set; }
        public virtual DbSet<SL_VISITOR> SL_VISITOR { get; set; }
        public virtual DbSet<SLEOC_TEAM> SLEOC_TEAM { get; set; }
        public virtual DbSet<SLEOC_TEAM_MEMBER> SLEOC_TEAM_MEMBER { get; set; }
    }
}
